strip = neopixel.create(DigitalPin.P8, 4, NeoPixelMode.RGB)
strip.clear()

def on_forever():
    strip.show_color(neopixel.colors(NeoPixelColors.RED))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.ORANGE))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.YELLOW))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.GREEN))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.BLUE))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.INDIGO))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.VIOLET))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.PURPLE))
    basic.pause(1000)
    strip.show_color(neopixel.colors(NeoPixelColors.WHITE))
    basic.pause(1000)
basic.forever(on_forever)
